name: dart_parallelpi
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0-116.0.dev <3.0.0'


dependencies:
  path: ^1.8.0
  pmap: ^0.3.0
  collection:

dev_dependencies:
  lints: ^1.0.0
